version: '3.8'

services:
  # Flask API
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=False
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./api:/app
    networks:
      - solarwind-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - solarwind-network
    restart: unless-stopped

networks:
  solarwind-network:
    driver: bridge 